### PR TITLE
fix: actually write cloud events by awaiting the repository save in the storming sinks

### LINKED ISSUE #141: cloud-event-storming sinks never subscribe the repository save, and only persist by accident through Spring's event multicaster
## Summary

Both `@EventListener` sinks of `f2-feature/cloud-event-storming` end their body with a bare, unsubscribed `repo.save(entity)` wrapped in a `runBlocking` that suspends nothing:

```kotlin
// StormingCommandSink.kt / StormingCloudEventSink.kt
@EventListener
fun storeCommand(event: CloudEvent<*>) = runBlocking {
    val entity = CloudEventEntity(id = UUID.randomUUID(), event = event)
    repo.save(entity)   // cold Mono, returned, never subscribed here
}
```

`ReactiveCrudRepository.save` returns a cold `Mono`: nothing happens until someone subscribes. The `runBlocking` block contains no suspension point, so it only builds the publisher and hands it back — the listener's return type is `Mono<CloudEventEntity>`.

## Measured behaviour (Spring Framework 7.0.8 / Boot 4.1)

Probed with an in-memory `ReactiveCrudRepository` whose `save` is a `Mono.fromCallable`:

| path | `save()` calls | rows written |
| --- | --- | --- |
| direct invocation (`sink.storeCommand(event)`) | 1 | **0** |
| published through the application event multicaster | 1 | 1 |

So the claim "the feature persists nothing" is only true for direct invocation. Through the multicaster the row *is* written, but by accident rather than by design: `ApplicationListenerMethodAdapter.ReactiveResultHandler` detects the returned `Publisher` and subscribes to it with an `EventPublicationSubscriber`. That implicit rescue has real consequences:

1. **Persistence is fire-and-forget.** The subscription is not awaited; with a real R2DBC repository the insert completes some time after the listener returned. Nothing downstream can know whether the event was stored.
2. **Failures are invisible to the publisher.** A save error reaches `EventPublicationSubscriber.onError` → `handleAsyncError`, i.e. it is logged and dropped. The component that published the command sees a success.
3. **The saved entity is re-published as an application event.** `EventPublicationSubscriber.onNext` calls `publishEvents(...)`, so every store emits a spurious `CloudEventEntity` application event. Verified: a catch-all `@EventListener(Any)` in the same context observes `[ContextRefreshedEvent, CloudEventEntity, CloudEvent]` for a single published cloud event.
4. **Nothing is stored outside the multicaster path** — direct calls, manual wiring, tests.
5. The `runBlocking` wrapper is misleading: it suggests the write is awaited, and it does nothing at all.

## Proposed fix

Subscribe/await the reactive call inside the coroutine and return `Unit`, so the write really happens, errors propagate to the publisher, and no follow-up event is emitted:

```kotlin
@EventListener
fun storeCommand(event: CloudEvent<*>) {
    runBlocking { repo.save(entity).awaitSingle() }
}
```

Trade-off: the listener becomes blocking on the publishing thread. That is the behaviour the current `runBlocking` already advertises, and it is what makes the audit trail reliable; making the sinks fully non-blocking (suspending listeners / `@Async`) is a larger, separate design change.

## Adjacent problems found, deliberately left alone

Reported here rather than fixed, because fixing them widens the change well beyond the missing subscription:

* **Id type mismatch.** `CloudEventEntityRepository : ReactiveCrudRepository<CloudEventEntity, String>` while `CloudEventEntity.id` is a `UUID`. Every id-based method (`findById`, `existsById`, `deleteById`) is typed `String`; against a real store this is at best a silent conversion, at worst a runtime failure. The repository interface is public API of the module, so retyping it to `UUID` is a breaking change.
* **JPA entity under a reactive repository.** `CloudEventEntity` is annotated `jakarta.persistence.@Entity` (blocking JPA) with a `org.springframework.data.annotation.@Id`, yet it is served by a `ReactiveCrudRepository` built from the host application's `ReactiveRepositoryFactorySupport`. JPA cannot back a reactive repository; an R2DBC mapping (`@Table`, `org.springframework.data.annotation.@Id`) is what this needs.
* **Unmappable column.** `val event: CloudEvent<*>` is an open generic class with no column type and no registered converter, so no relational store can map it as-is. It needs an explicit converter (e.g. serialise to `json`/`text`) or a serialised `String` column. The module ships no driver and no schema, so this only surfaces in a host application.

_Found while adding tests (PR #136)._

### PR DESCRIPTION
**Pull request by apoupard**
Closes #141.

## The bug

`StormingCommandSink.storeCommand` and `StormingCloudEventSink.storeCommand` both ended with

```kotlin
fun storeCommand(event: CloudEvent<*>) = runBlocking {
    ...
    repo.save(entity)   // cold Mono, returned, never subscribed
}
```

`ReactiveCrudRepository.save` is cold and the `runBlocking` block contains no suspension point, so
the listener only *built* the publisher. Measured with an in-memory reactive repository:

| path | `save()` calls | rows written |
| --- | --- | --- |
| direct invocation | 1 | **0** |
| published through the application event multicaster | 1 | 1 |

Through the multicaster the row was written only by accident:
`ApplicationListenerMethodAdapter.ReactiveResultHandler` subscribes to a `Publisher` returned by an
`@EventListener`, and its `EventPublicationSubscriber` re-publishes each emitted element as an
application event — a catch-all listener observed `[ContextRefreshedEvent, CloudEventEntity,
CloudEvent]` for a single published cloud event.

## What changed

Both sinks are now suspending listeners, and (as requested in review) the repository is now a
Kotlin coroutine repository, so the save is a plain suspending call:

```kotlin
@EventListener
suspend fun storeCommand(event: CloudEvent<*>) {
    ...
    repo.save(entity)
}
```

Spring Framework 7 supports suspending `@EventListener` methods natively: `ApplicationListenerMethodAdapter`
detects them with `KotlinDetector.isSuspendingFunction` and invokes them through
`CoroutinesUtils.invokeSuspendingFunction`, which wraps the call in a `Mono` and subscribes to it.
The save is complete when the suspending call returns — the row is written on every path, not only
through the multicaster — and no thread is blocked.

The listeners return `Unit` on purpose: `CoroutinesUtils` ends with
`.filter(result -> result != Unit.INSTANCE)`, so nothing is emitted and no `CloudEventEntity` is
re-published as a follow-up application event. Letting the signature drift to a value-returning form
would bring that spurious re-publication back; a test pins this.

### The repository is now a coroutine repository (breaking for host applications)

`CloudEventEntityRepository` now extends
`CoroutineCrudRepository<CloudEventEntity, UUID>` instead of
`ReactiveCrudRepository<CloudEventEntity, String>`. Two breaks for anyone consuming the interface:

* **Signatures**: `Mono`/`Flux` → `suspend` functions and `Flow` (`save` is `suspend`, `findAll()`
  returns `Flow<CloudEventEntity>`, …).
* **Id type**: `String` → `UUID`, matching `CloudEventEntity.id` (the mismatch was flagged in #141).
  Since every method signature changes anyway with the coroutine conversion, the id is fixed in the
  same stroke rather than breaking the interface twice.

The `cloudEvents` supplier follows: `Supplier<Flux<CloudEvent<*>>>` → `Supplier<Flow<CloudEvent<*>>>`
(no conversion needed — `findAll()` already is a `Flow`).

The bean wiring is unchanged: the module still declares no persistence driver, and
`F2StormingCloudEventConfig` still materialises the repository from the host application's
`ReactiveRepositoryFactorySupport` — coroutine repositories ride the reactive repository
infrastructure. `F2StormingCloudEventConfigTest` now proves this instead of assuming it: the factory
stub no longer short-circuits `getRepository`, so the real factory machinery builds the proxy for
the `CoroutineCrudRepository`-based interface, and the test round-trips `save`/`findAll`/`findById`
through it.

### Persistence is asynchronous fire-and-forget

Stated plainly, because it is a behaviour change for callers:

* the write is **not** guaranteed to be complete when `publishEvent` returns — Spring subscribes to
  the `Mono` wrapping the suspending listener and does not wait for it;
* a repository failure is **not** propagated to the publisher of the event. It surfaces on Spring's
  asynchronous listener error path, i.e. logged as
  `ERROR ApplicationListenerMethodAdapter -- Unexpected error occurred in asynchronous listener`.

This is the accepted trade-off: the alternative (`runBlocking` inside the listener) makes the write
synchronous and error-propagating but blocks the publishing thread, which is not acceptable in a
WebFlux application.

### New dependency

`kotlinx-coroutines-reactor` is added to the module, and must stay even though no module code
imports reactor anymore: `CoroutinesUtils` builds its `Mono` through
`kotlinx.coroutines.reactor.MonoKt`; with only `kotlinx-coroutines-reactive` on the classpath a
suspending listener throws `NoClassDefFoundError: kotlinx/coroutines/reactor/MonoKt` at
`publishEvent` — verified by removing the dependency again: the two `ApplicationContext` tests fail
exactly that way. Spring Data uses the same bridge to back the coroutine repository with the host's
reactive infrastructure.

## How it was verified

Targeted only, no full build:

* `./gradlew :f2-feature:cloud-event-storming:f2-feature-cloud-event-storming:test` — 23 tests, 0 failures.
* `./gradlew :f2-feature:cloud-event-storming:f2-feature-cloud-event-storming:detekt` — clean.

Two tests were removed with the coroutine conversion (25 → 23):
`storeCommand awaits the save instead of returning a cold Mono` in each sink test existed only to
pin the reactive interface's laziness (`saveInvocations` vs `saved`, i.e. "invoked" vs
"subscribed"). A suspending `save` cannot return a cold publisher — completion on return is the type
system's guarantee — and the remaining tests already assert the write happened. Every behavioral
assertion is otherwise kept.

`StormingSinkPersistenceTest` (in-memory coroutine repository) covers:

* each sink has written when the direct suspending call returns;
* the command sink stores the serialised command;
* each stored event gets its own entity id;
* a repository failure propagates to a *direct* caller of the suspending function;
* an event published in a real `ApplicationContext` is stored exactly once, and no
  `CloudEventEntity` is observed by a catch-all listener as a follow-up application event;
* a repository failure published through the context does **not** throw out of `publishEvent` and
  writes nothing — the async behaviour described above.

## Evaluated, deliberately not fixed (see #141)

* `CloudEventEntity` is a JPA `@Entity` (blocking) served by a reactive-infrastructure repository,
  and `val event: CloudEvent<*>` (an open generic class) has no column mapping or converter. Making
  this actually persistable in a host application is a schema/mapping redesign, not a subscription
  fix.

## Summary by CodeRabbit

- **New Features**
  - Added coroutine-based persistence for commands and cloud events.
  - Cloud event retrieval now supports Kotlin Flow.
  - Event listeners persist asynchronously while routing failures through Spring’s listener error handling.
  - Cloud event identifiers now use UUIDs.

- **Bug Fixes**
  - Improved event persistence reliability and failure isolation.
  - Prevented unrelated events from being persisted or republished.

- **Tests**
  - Expanded coverage for persistence, serialization, asynchronous handling, error propagation, and event wiring.

### CODE REVIEW

**Comment by apoupard** [comment]
## Evaluated `@EventListener suspend fun` as an alternative to `runBlocking` — keeping `runBlocking`

The obvious objection to this PR is that `runBlocking` blocks the publishing thread in a reactive
app, and Spring supports suspending `@EventListener` methods natively. I measured both variants
instead of reasoning about them. **Suspending listeners work, but they are asynchronous
fire-and-forget: they give up exactly the two guarantees this PR was after.** So this branch stays
as is.

### Is it supported here?

Yes. Spring Boot 4.1.0 resolves **Spring Framework 7.0.8**; the loaded class is
`spring-context-7.0.8.jar` (`.../org.springframework/spring-context/7.0.8/6c58b590.../spring-context-7.0.8.jar`).
`ApplicationListenerMethodAdapter` in that exact artifact has:

* L129 — `KotlinDetector.isSuspendingFunction(method) ? method.getParameterCount() - 1 : ...`
  (so the trailing `Continuation` is not counted as the event parameter);
* L389-390 — `if (KotlinDetector.isSuspendingFunction(this.method)) return CoroutinesUtils.invokeSuspendingFunction(this.method, bean, args);`

One practical gotcha: `CoroutinesUtils` builds the `Mono` via `kotlinx.coroutines.reactor.MonoKt`.
This module only declares `kotlinx-coroutines-reactive`, so with a suspending listener as-is,
`publishEvent` fails with `NoClassDefFoundError: kotlinx/coroutines/reactor/MonoKt`. Converting the
sinks would require adding `kotlinx-coroutines-reactor` to the module.

### Measured semantics

Both sink shapes were run in a real `AnnotationConfigApplicationContext` against three repositories:
a synchronous one (`Mono.fromCallable`), a genuinely asynchronous one (`Mono.delay(300ms)` then
write on another thread — i.e. what a real R2DBC repository looks like), and a failing one.

| repository | listener | write done when `publishEvent` returned? | failure reaches `publishEvent`? |
| --- | --- | --- | --- |
| synchronous | `fun` + `runBlocking` (this PR) | **yes** | **yes** — `IllegalStateException` |
| synchronous | `suspend fun` | yes (by accident, see below) | — |
| asynchronous | `fun` + `runBlocking` (this PR) | **yes** | — |
| asynchronous | `suspend fun` | **no** — nothing had run yet | — |
| failing | `fun` + `runBlocking` (this PR) | — | **yes** — `IllegalStateException` |
| failing | `suspend fun` | — | **no** — `publishEvent` returned normally |

For the failing + `suspend fun` row, the only trace of the lost write was on the adapter's own logger:

```
ERROR o.s.c.event.ApplicationListenerMethodAdapter -- Unexpected error occurred in asynchronous listener
```

That is `handleAsyncError`, reached through `ReactiveResultHandler` → `EventPublicationSubscriber.onError`
— the same swallow-and-log path the pre-fix code fell into, which is what #141 is about.

**Why the synchronous case looks ordered.** `CoroutinesUtils.invokeSuspendingFunction` runs the
coroutine on `Dispatchers.Unconfined`, so the body executes eagerly on the publishing thread *up to
the first real suspension*. If the repository's `Mono` completes synchronously, the whole listener
finishes inside `publishEvent` and everything looks fine. Against a real reactive driver it does not
— row 4 above. So ordering with a suspending listener is not a guarantee, it is an artifact of the
repository being synchronous, and it silently disappears in production.

### Re-publication (the third thing this PR fixed)

`CoroutinesUtils` ends with `.filter(result -> result != Unit.INSTANCE)`, so a **`Unit`-returning**
suspending listener does *not* re-publish anything — that axis is fine. But a suspending listener
returning a value does: with `suspend fun on(e: Payload): StoredEntity`, the catch-all listener
observed `[StoredEntity, Payload]`. The `Unit` return type in this PR is what keeps that shut, in
both shapes.

### Options

1. **`fun` + `runBlocking` + `Unit` (this PR).** Write completes before `publishEvent` returns, a
   repository failure propagates to the publisher, nothing is re-published. Cost: the publishing
   thread is blocked for the duration of the write.
2. **`suspend fun`.** Non-blocking, but the write is fire-and-forget, a failed write is only logged,
   and callers cannot read-after-publish. Also needs `kotlinx-coroutines-reactor`. This re-opens
   #141 in a quieter form.
3. **Take the write off `@EventListener` entirely** — expose `suspend fun store(event): Unit` (or a
   `Mono`-returning API) on the sinks and let callers compose it into their own reactive chain. That
   is the only shape that is non-blocking *and* ordered *and* propagates errors. It is also a
   breaking API change for every publisher in host applications, since today the sinks are driven
   purely by whatever the host publishes as `Command` / `CloudEvent<*>`.

**Recommendation: keep option 1 for this bugfix.** It is the minimal change that makes the sinks
correct, and the blocking it introduces is the blocking the code already advertised with its
pre-existing `runBlocking`. Option 2 is not an improvement — it trades a thread-blocking write for a
silently-droppable one, which is the defect being fixed. If the blocking becomes a real problem,
option 3 is the right follow-up, tracked separately: it is an API design change, not a subscription
fix.

<sub>Measured on `fix/storming-event-persistence`; the experiment was a scratch test and is not
committed. Module verification unchanged: 5 tests pass, detekt clean.</sub>

**Comment by apoupard** [comment]
Changed approach on this branch (53b3481): the sinks are now suspending `@EventListener` methods that `await` the repository save directly, instead of wrapping it in `runBlocking`. Spring Framework 7 invokes suspending listeners through `CoroutinesUtils.invokeSuspendingFunction`, so the cold `Mono` is really subscribed on every path without blocking the publishing thread.

Consequence, spelled out in the description: persistence is now asynchronous fire-and-forget. The write is not guaranteed to be complete when `publishEvent` returns, and a repository failure is not propagated to the publisher — Spring logs it on its async listener error path. The listeners keep returning `Unit`, which `CoroutinesUtils` filters out, so no `CloudEventEntity` is re-published as a follow-up application event.

This needs a new dependency: `kotlinx-coroutines-reactor` (alias already in the version catalogue). `CoroutinesUtils` builds its `Mono` via `kotlinx.coroutines.reactor.MonoKt`, so with only `kotlinx-coroutines-reactive` a suspending listener throws `NoClassDefFoundError: kotlinx/coroutines/reactor/MonoKt` at `publishEvent`.

Tests rewritten accordingly: 6 tests, 0 failures; detekt clean. The one that asserted a failure reaching `publishEvent` now asserts the honest behaviour — `publishEvent` does not throw and nothing is written — and a separate test still covers propagation to a direct caller of the suspending function.

**Comment by apoupard** [comment]
Merged `main` into this branch (merge commit, no force-push) to resolve the conflicts introduced by #136 landing first.

**Conflicts resolved**
- `build.gradle.kts` — kept both sides: this branch's `kotlinx-coroutines-reactor` (required by Spring's `CoroutinesUtils` to invoke suspending `@EventListener` methods) and main's `testImplementation(libs.spring.tx)`.
- `InMemoryCloudEventEntityRepository.kt` (add/add) — kept this branch's `open class` plus the KDoc noting `save` is deliberately lazy; the class bodies were otherwise identical.

**#136's tests adapted to the suspending signature**
`storeCommand` is now `suspend fun … : Unit`, so `.block()` no longer applies. Converted the call sites in `StormingCommandSinkTest`, `StormingCloudEventSinkTest` and `F2StormingCloudEventConfigTest` to `@Test suspend fun` (repo house style — JUnit 6.1 supports suspending test functions) and dropped `.block()`.

Two of #136's tests asserted the **old defect** (`storeCommand currently returns a cold Mono and persists nothing until it is subscribed`). Those claims are false now, so rather than delete the coverage they were inverted into `storeCommand awaits the save instead of returning a cold Mono`, asserting the row *is* written — i.e. they now pin the fix instead of the bug.

`.block()` calls on `repository.save(...)` and `supplier.get().collectList()` were left untouched: those are genuinely reactive APIs, unrelated to the sink signature.

**Verification** — 25 tests, 0 failures, 0 skipped (19 from #136 + 6 from this branch, so no coverage lost); detekt clean.

**Comment by apoupard** [comment]
As requested: `CloudEventEntityRepository` is now a coroutine repository (374e00b) — it extends `CoroutineCrudRepository<CloudEventEntity, UUID>` instead of `ReactiveCrudRepository<CloudEventEntity, String>`. The sinks save with a plain suspending call, the `cloudEvents` supplier exposes a `Flow`, and the id type is fixed to `UUID` in the same stroke since every signature was changing anyway. The config test now materialises the repository through the real `ReactiveRepositoryFactorySupport.getRepository` path to prove the host's reactive factory can build the coroutine proxy. PR body updated accordingly.
